### ISSUE TITLE
Add sleep(1) before exit call when printing

### ISSUE THREAD

**Issue by skliper** [nasa/PSP#299]
**Is your feature request related to a problem? Please describe.**
User reported OS_print doesn't display before exit, for example:
https://github.com/nasa/PSP/blob/6d40816cfcc2836182f04bacf7d98b7d5cf5163b/fsw/pc-linux/src/cfe_psp_memory.c#L145-L146

**Describe the solution you'd like**
Add sleep(1) between prints and exits to give it a chance

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Similar/related issue to #203 (this is the symptom anyway).  I may even have a patch/fix that was never merged for that issue already done somewhere from when I quickly looked at it.

Note that use of `sleep` system call is discouraged for new code as it may interfere with other timers.  `nanosleep` (POSIX) or even OS_TaskDelay might be preferable.

**Comment by pavll** [comment]
Ok, I now used the OS_TaskDelay since it's the implemented behaviour of the OSAL package but maybe I could use fflush(stdout) if someone who knows the project can give a short feedback on this. And if OS_TaskDelay is used maybe only 100 milliseconds are required because this value is already used in:
https://github.com/nasa/PSP/blob/6d40816cfcc2836182f04bacf7d98b7d5cf5163b/fsw/pc-linux/src/cfe_psp_start.c#L468-L474
