### ISSUE TITLE
CFE_PSP_Module_FindByName does not find base modules

### ISSUE THREAD

**Issue by jphickey** [nasa/PSP#393]
**Describe the bug**
PSP modules can be enabled in two ways, either by adding to the `${cpuname}_PSP_MODULELIST` in targets.cmake (for optional/platform-specific hardware access routines) or a set of "standard" modules listed in `psp_module_list.cmake` file under the PSP.

Problem is that `CFE_PSP_Module_FindByName()` only looks at the user-specified list (from targets.cmake) and not the list of standard modules.

This is needed for HS because the `linux_sysmon` monitor (for cpu utilization) is now listed as a standard module for pc-linux PSP, but this inadvertently made it un-findable.

**To Reproduce**
Run the current build of framework + HS app (which relies on being able to locate the `linux_sysmon` module).  HS does not find a module and disables CPU usage reporting.

**Expected behavior**
HS should find the module and enable usage reporting

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by avan989** [comment]
@jphickey @dmknutsen  It looks like it was intentional from the comments that only the global_config. PspModuleList was supposed to use CFE_PSP_Module_FindByName() and not the base_module. Do we still want to change it so it can look up both lists?

Note:
CFE_PSP_Module_GetAPIEntry also needs to be updated to work.

https://github.com/nasa/PSP/blob/47d2c1e052a615d5aac9008f979333236ec23531/fsw/shared/src/cfe_psp_module.c#L45-L52
https://github.com/nasa/PSP/blob/47d2c1e052a615d5aac9008f979333236ec23531/fsw/shared/src/cfe_psp_module.c#L98-L103
